import * as React from 'react';
import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import '@pigment-css/react/styles.css';
import './globals.css';
import App from '@/components/App';
import { ColorSchemeProvider } from '@/components/ColorScheme/ColorSchemeProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout(props: { children: React.ReactNode }) {
  const cookieStore = await cookies();
  const { value: colorScheme = 'light' } = cookieStore.get('colorScheme') ?? {};
  return (
    <html lang="en">
      <ColorSchemeProvider colorScheme={colorScheme}>
        <App>{props.children}</App>
      </ColorSchemeProvider>
    </html>
  );
}
